# Generated by Django 4.0.2 on 2022-02-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave'), ('paternity', 'Paternity Leave'), ('maternity', 'Maternity Leave')], max_length=50),
        ),
    ]
